using System;
using System.Collections.Generic;

namespace PCRClient.Models.Db
{
    public partial class FixLineupGroupSet
    {
        public long LineupGroupSetId { get; set; }
        public long TeamLevelFrom { get; set; }
        public long TeamLevelTo { get; set; }
        public long RewardType1 { get; set; }
        public long RewardId1 { get; set; }
        public long RewardCount1 { get; set; }
        public long PriceType1 { get; set; }
        public long CurrencyId1 { get; set; }
        public long Price1 { get; set; }
        public long RewardType2 { get; set; }
        public long RewardId2 { get; set; }
        public long RewardCount2 { get; set; }
        public long PriceType2 { get; set; }
        public long CurrencyId2 { get; set; }
        public long Price2 { get; set; }
        public long RewardType3 { get; set; }
        public long RewardId3 { get; set; }
        public long RewardCount3 { get; set; }
        public long PriceType3 { get; set; }
        public long CurrencyId3 { get; set; }
        public long Price3 { get; set; }
        public long RewardType4 { get; set; }
        public long RewardId4 { get; set; }
        public long RewardCount4 { get; set; }
        public long PriceType4 { get; set; }
        public long CurrencyId4 { get; set; }
        public long Price4 { get; set; }
        public long RewardType5 { get; set; }
        public long RewardId5 { get; set; }
        public long RewardCount5 { get; set; }
        public long PriceType5 { get; set; }
        public long CurrencyId5 { get; set; }
        public long Price5 { get; set; }
        public long RewardType6 { get; set; }
        public long RewardId6 { get; set; }
        public long RewardCount6 { get; set; }
        public long PriceType6 { get; set; }
        public long CurrencyId6 { get; set; }
        public long Price6 { get; set; }
        public long RewardType7 { get; set; }
        public long RewardId7 { get; set; }
        public long RewardCount7 { get; set; }
        public long PriceType7 { get; set; }
        public long CurrencyId7 { get; set; }
        public long Price7 { get; set; }
        public long RewardType8 { get; set; }
        public long RewardId8 { get; set; }
        public long RewardCount8 { get; set; }
        public long PriceType8 { get; set; }
        public long CurrencyId8 { get; set; }
        public long Price8 { get; set; }
        public long RewardType9 { get; set; }
        public long RewardId9 { get; set; }
        public long RewardCount9 { get; set; }
        public long PriceType9 { get; set; }
        public long CurrencyId9 { get; set; }
        public long Price9 { get; set; }
        public long RewardType10 { get; set; }
        public long RewardId10 { get; set; }
        public long RewardCount10 { get; set; }
        public long PriceType10 { get; set; }
        public long CurrencyId10 { get; set; }
        public long Price10 { get; set; }
        public long RewardType11 { get; set; }
        public long RewardId11 { get; set; }
        public long RewardCount11 { get; set; }
        public long PriceType11 { get; set; }
        public long CurrencyId11 { get; set; }
        public long Price11 { get; set; }
        public long RewardType12 { get; set; }
        public long RewardId12 { get; set; }
        public long RewardCount12 { get; set; }
        public long PriceType12 { get; set; }
        public long CurrencyId12 { get; set; }
        public long Price12 { get; set; }
        public long RewardType13 { get; set; }
        public long RewardId13 { get; set; }
        public long RewardCount13 { get; set; }
        public long PriceType13 { get; set; }
        public long CurrencyId13 { get; set; }
        public long Price13 { get; set; }
        public long RewardType14 { get; set; }
        public long RewardId14 { get; set; }
        public long RewardCount14 { get; set; }
        public long PriceType14 { get; set; }
        public long CurrencyId14 { get; set; }
        public long Price14 { get; set; }
        public long RewardType15 { get; set; }
        public long RewardId15 { get; set; }
        public long RewardCount15 { get; set; }
        public long PriceType15 { get; set; }
        public long CurrencyId15 { get; set; }
        public long Price15 { get; set; }
        public long RewardType16 { get; set; }
        public long RewardId16 { get; set; }
        public long RewardCount16 { get; set; }
        public long PriceType16 { get; set; }
        public long CurrencyId16 { get; set; }
        public long Price16 { get; set; }
        public long RewardType17 { get; set; }
        public long RewardId17 { get; set; }
        public long RewardCount17 { get; set; }
        public long PriceType17 { get; set; }
        public long CurrencyId17 { get; set; }
        public long Price17 { get; set; }
        public long RewardType18 { get; set; }
        public long RewardId18 { get; set; }
        public long RewardCount18 { get; set; }
        public long PriceType18 { get; set; }
        public long CurrencyId18 { get; set; }
        public long Price18 { get; set; }
        public long RewardType19 { get; set; }
        public long RewardId19 { get; set; }
        public long RewardCount19 { get; set; }
        public long PriceType19 { get; set; }
        public long CurrencyId19 { get; set; }
        public long Price19 { get; set; }
        public long RewardType20 { get; set; }
        public long RewardId20 { get; set; }
        public long RewardCount20 { get; set; }
        public long PriceType20 { get; set; }
        public long CurrencyId20 { get; set; }
        public long Price20 { get; set; }
    }
}
